//! HTML output format for the publish pipeline.
//!
//! Implements [`PublishFormat`] using comrak for markdown-to-HTML conversion,
//! with custom syntax preprocessing (highlights, spoilers), link rewriting,
//! metadata pills, and a built-in CSS stylesheet.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use crate::entry::slugify;
use crate::frontmatter;
use crate::link_parser;

use super::publish_format::PublishFormat;
use super::types::{NavLink, PublishedPage};

/// HTML output format backed by comrak.
pub struct HtmlFormat;

impl PublishFormat for HtmlFormat {
    fn output_extension(&self) -> &str {
        "html"
    }

    fn preprocess_body(&self, markdown: &str) -> String {
        preprocess_custom_syntax(markdown)
    }

    fn convert_body(&self, preprocessed_markdown: &str) -> String {
        use comrak::{Options, markdown_to_html};

        let mut options = Options::default();
        options.extension.strikethrough = true;
        options.extension.table = true;
        options.extension.autolink = true;
        options.extension.tasklist = true;
        options.extension.footnotes = true;
        options.render.r#unsafe = true; // Allow raw HTML

        markdown_to_html(preprocessed_markdown, &options)
    }

    fn transform_links(
        &self,
        html: &str,
        current_path: &Path,
        path_to_filename: &HashMap<PathBuf, String>,
        workspace_dir: &Path,
        dest_filename: &str,
    ) -> String {
        let prefix = root_prefix(dest_filename);
        // to_canonical expects workspace-relative paths
        let current_relative = current_path
            .strip_prefix(workspace_dir)
            .unwrap_or(current_path);

        let mut result = String::with_capacity(html.len());
        let mut remaining = html;

        while let Some(href_start) = remaining.find("href=\"") {
            result.push_str(&remaining[..href_start + 6]);
            remaining = &remaining[href_start + 6..];

            if let Some(href_end) = remaining.find('"') {
                let rest = &remaining[href_end..];
                let raw_href = &remaining[..href_end];

                if raw_href.ends_with(".md")
                    && !raw_href.starts_with("http://")
                    && !raw_href.starts_with("https://")
                    && !raw_href.starts_with('#')
                {
                    let decoded_href = super::publisher::percent_decode(raw_href);
                    let parsed = link_parser::parse_link(&decoded_href);
                    let canonical = link_parser::to_canonical(&parsed, current_relative);
                    let target_path = workspace_dir.join(&canonical);

                    let html_path =
                        path_to_filename
                            .get(&target_path)
                            .cloned()
                            .unwrap_or_else(|| {
                                Path::new(&canonical)
                                    .with_extension("html")
                                    .to_string_lossy()
                                    .into_owned()
                            });

                    result.push_str(&format!("{}{}", prefix, html_path));
                } else {
                    result.push_str(raw_href);
                }

                remaining = rest;
            }
        }
        result.push_str(remaining);

        result
    }

    fn render_page(&self, page: &PublishedPage, site_title: &str, single_file: bool) -> String {
        let prefix = root_prefix(&page.dest_filename);
        let css_link = if single_file {
            format!("<style>{}</style>", get_css())
        } else {
            format!(r#"<link rel="stylesheet" href="{}style.css">"#, prefix)
        };

        let breadcrumb_html = render_breadcrumb(page, single_file);
        let pill_html = render_metadata_pill(page, single_file);

        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{page_title} - {site_title}</title>
    {css_link}
</head>
<body>
    <header>
        <h1 class="site-title"><a href="{root_prefix}index.html">{site_title}</a></h1>
    </header>
    <main>
        <article>
            {breadcrumb}
            <div class="content">
                {content}
            </div>
        </article>
    </main>
    {pill}
    <footer>
        <p>Generated by <a href="https://github.com/diaryx-org/diaryx-core">diaryx</a></p>
    </footer>
    <script>
    (function() {{
        if ('ontouchstart' in window || navigator.maxTouchPoints > 0) {{
            var pill = document.querySelector('.metadata-pill');
            if (pill) {{
                pill.addEventListener('click', function(e) {{
                    e.stopPropagation();
                    pill.classList.toggle('is-active');
                }});
                document.addEventListener('click', function() {{
                    pill.classList.remove('is-active');
                }});
            }}
        }}
        document.querySelectorAll('.spoiler-mark').forEach(function(el) {{
            el.addEventListener('click', function() {{
                el.classList.toggle('spoiler-hidden');
                el.classList.toggle('spoiler-revealed');
            }});
        }});
    }})();
    </script>
</body>
</html>"#,
            page_title = html_escape(&page.title),
            site_title = html_escape(site_title),
            root_prefix = prefix,
            css_link = css_link,
            breadcrumb = breadcrumb_html,
            content = page.rendered_body,
            pill = pill_html,
        )
    }

    fn render_single_document(&self, pages: &[PublishedPage], site_title: &str) -> String {
        let mut sections = Vec::new();

        for page in pages {
            let anchor = title_to_anchor(&page.title);
            let breadcrumb = render_breadcrumb(page, true);
            let metadata = render_metadata_details(page);

            sections.push(format!(
                r#"<section id="{anchor}">
    {breadcrumb}
    {metadata}
    <div class="content">
        {content}
    </div>
</section>"#,
                anchor = html_escape(&anchor),
                breadcrumb = breadcrumb,
                metadata = metadata,
                content = page.rendered_body,
            ));
        }

        // Build table of contents
        let mut toc = String::from(r#"<nav class="toc"><h2>Table of Contents</h2><ul>"#);
        for page in pages {
            let anchor = title_to_anchor(&page.title);
            toc.push_str(&format!(
                r##"<li><a href="#{}">{}</a></li>"##,
                html_escape(&anchor),
                html_escape(&page.title)
            ));
        }
        toc.push_str("</ul></nav>");

        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{site_title}</title>
    <style>{css}</style>
</head>
<body>
    <header>
        <h1 class="site-title">{site_title}</h1>
    </header>
    <main>
        {toc}
        {sections}
    </main>
    <footer>
        <p>Generated by <a href="https://github.com/diaryx-org/diaryx-core">diaryx</a></p>
    </footer>
    <script>
    (function() {{
        document.querySelectorAll('.spoiler-mark').forEach(function(el) {{
            el.addEventListener('click', function() {{
                el.classList.toggle('spoiler-hidden');
                el.classList.toggle('spoiler-revealed');
            }});
        }});
    }})();
    </script>
</body>
</html>"#,
            site_title = html_escape(site_title),
            css = get_css(),
            toc = toc,
            sections = sections.join("\n<hr>\n"),
        )
    }

    fn static_assets(&self) -> Vec<(String, Vec<u8>)> {
        vec![("style.css".to_string(), get_css().as_bytes().to_vec())]
    }
}

// ============================================================================
// Helper functions
// ============================================================================

/// Compute the relative prefix to get from a page back to the site root.
pub(crate) fn root_prefix(dest_filename: &str) -> String {
    let depth = dest_filename.matches('/').count();
    if depth == 0 {
        String::new()
    } else {
        "../".repeat(depth)
    }
}

/// Convert a title to an anchor ID.
fn title_to_anchor(title: &str) -> String {
    slugify(title)
}

/// Escape HTML special characters.
pub(crate) fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

/// Render a serde_yaml::Value as HTML for the metadata pill.
fn render_frontmatter_value(value: &serde_yaml::Value) -> String {
    match value {
        serde_yaml::Value::String(s) => html_escape(s),
        serde_yaml::Value::Number(n) => html_escape(&n.to_string()),
        serde_yaml::Value::Bool(b) => html_escape(&b.to_string()),
        serde_yaml::Value::Null => "\u{2014}".to_string(), // em-dash
        serde_yaml::Value::Sequence(seq) => seq
            .iter()
            .map(render_frontmatter_value)
            .collect::<Vec<_>>()
            .join("<br>"),
        serde_yaml::Value::Mapping(_) => {
            let yaml = serde_yaml::to_string(value).unwrap_or_default();
            format!("<pre>{}</pre>", html_escape(yaml.trim()))
        }
        serde_yaml::Value::Tagged(t) => render_frontmatter_value(&t.value),
    }
}

/// Render breadcrumb navigation (parent link above the title).
fn render_breadcrumb(page: &PublishedPage, single_file: bool) -> String {
    let prefix = root_prefix(&page.dest_filename);
    if let Some(ref parent) = page.parent_link {
        let href = if single_file {
            format!("#{}", title_to_anchor(&parent.title))
        } else {
            format!("{}{}", prefix, parent.href)
        };
        format!(
            r#"<nav class="breadcrumb" aria-label="Breadcrumb"><a href="{}">{}</a></nav>"#,
            html_escape(&href),
            html_escape(&parent.title),
        )
    } else {
        String::new()
    }
}

/// Render the floating metadata pill for a page.
fn render_metadata_pill(page: &PublishedPage, single_file: bool) -> String {
    if page.frontmatter.is_empty() {
        return String::new();
    }

    let prefix = root_prefix(&page.dest_filename);

    // Build collapsed pill summary: title · author · audience
    let title = frontmatter::get_string(&page.frontmatter, "title");
    let author = frontmatter::get_string(&page.frontmatter, "author");
    let audience_val = page.frontmatter.get("audience");
    let audience_str = audience_val.and_then(|v| match v {
        serde_yaml::Value::String(s) => Some(s.clone()),
        serde_yaml::Value::Sequence(seq) => {
            let parts: Vec<String> = seq
                .iter()
                .filter_map(|item| item.as_str().map(String::from))
                .collect();
            if parts.is_empty() {
                None
            } else {
                Some(parts.join(", "))
            }
        }
        _ => None,
    });

    let summary_parts: Vec<&str> = [title, author, audience_str.as_deref()]
        .into_iter()
        .flatten()
        .collect();
    let pill_summary = if summary_parts.is_empty() {
        "Document Info".to_string()
    } else {
        summary_parts.join(" \u{00b7} ") // middle dot
    };

    // Build expanded panel rows
    let mut rows = String::new();
    for (key, value) in &page.frontmatter {
        let rendered_value = if key == "contents" {
            render_contents_links(&page.contents_links, value, single_file, &prefix)
        } else if key == "part_of" {
            render_parent_link(&page.parent_link, value, single_file, &prefix)
        } else {
            render_frontmatter_value(value)
        };

        rows.push_str(&format!(
            r#"<div class="pill-row"><dt>{}</dt><dd>{}</dd></div>"#,
            html_escape(key),
            rendered_value
        ));
    }

    format!(
        r#"<div class="metadata-pill" role="complementary" aria-label="Document metadata">
    <div class="pill-collapsed"><span class="pill-text">{summary}</span></div>
    <div class="pill-expanded">
        <div class="pill-header"><span class="pill-header-label">Document Info</span></div>
        <div class="pill-content"><dl>{rows}</dl></div>
    </div>
</div>"#,
        summary = html_escape(&pill_summary),
        rows = rows,
    )
}

/// Render frontmatter as a collapsible `<details>` block for single-file mode.
fn render_metadata_details(page: &PublishedPage) -> String {
    if page.frontmatter.is_empty() {
        return String::new();
    }

    let mut rows = String::new();
    for (key, value) in &page.frontmatter {
        let rendered_value = if key == "contents" && !page.contents_links.is_empty() {
            render_links_as_anchors(&page.contents_links)
        } else if key == "part_of" {
            if let Some(ref parent) = page.parent_link {
                let href = format!("#{}", title_to_anchor(&parent.title));
                format!(
                    r#"<a href="{}">{}</a>"#,
                    html_escape(&href),
                    html_escape(&parent.title)
                )
            } else {
                render_frontmatter_value(value)
            }
        } else {
            render_frontmatter_value(value)
        };

        rows.push_str(&format!(
            r#"<div class="pill-row"><dt>{}</dt><dd>{}</dd></div>"#,
            html_escape(key),
            rendered_value
        ));
    }

    format!(
        r#"<details class="metadata-details"><summary>Document Info</summary><dl>{}</dl></details>"#,
        rows
    )
}

/// Render contents links as HTML for the metadata pill.
fn render_contents_links(
    links: &[NavLink],
    fallback_value: &serde_yaml::Value,
    single_file: bool,
    prefix: &str,
) -> String {
    if links.is_empty() {
        return render_frontmatter_value(fallback_value);
    }
    links
        .iter()
        .map(|link| {
            let href = if single_file {
                format!("#{}", title_to_anchor(&link.title))
            } else {
                format!("{}{}", prefix, link.href)
            };
            format!(
                r#"<a href="{}">{}</a>"#,
                html_escape(&href),
                html_escape(&link.title)
            )
        })
        .collect::<Vec<_>>()
        .join("<br>")
}

/// Render parent link as HTML for the metadata pill.
fn render_parent_link(
    parent: &Option<NavLink>,
    fallback_value: &serde_yaml::Value,
    single_file: bool,
    prefix: &str,
) -> String {
    if let Some(parent) = parent {
        let href = if single_file {
            format!("#{}", title_to_anchor(&parent.title))
        } else {
            format!("{}{}", prefix, parent.href)
        };
        format!(
            r#"<a href="{}">{}</a>"#,
            html_escape(&href),
            html_escape(&parent.title)
        )
    } else {
        render_frontmatter_value(fallback_value)
    }
}

/// Render links as anchor-only links (for single-file mode details).
fn render_links_as_anchors(links: &[NavLink]) -> String {
    links
        .iter()
        .map(|link| {
            let href = format!("#{}", title_to_anchor(&link.title));
            format!(
                r#"<a href="{}">{}</a>"#,
                html_escape(&href),
                html_escape(&link.title)
            )
        })
        .collect::<Vec<_>>()
        .join("<br>")
}

// ============================================================================
// Custom syntax preprocessing
// ============================================================================

/// Pre-process custom markdown syntax (highlights, spoilers) into raw HTML
/// before passing to comrak. Skips fenced code blocks and inline code.
fn preprocess_custom_syntax(markdown: &str) -> String {
    let bytes = markdown.as_bytes();
    let len = bytes.len();
    let mut out = String::with_capacity(len);
    let mut i = 0;

    while i < len {
        // Skip fenced code blocks (``` ... ```)
        if i + 2 < len && bytes[i] == b'`' && bytes[i + 1] == b'`' && bytes[i + 2] == b'`' {
            let fence_start = i;
            i += 3;
            while i < len && bytes[i] != b'\n' {
                i += 1;
            }
            loop {
                if i >= len {
                    out.push_str(&markdown[fence_start..]);
                    return out;
                }
                if bytes[i] == b'\n'
                    && i + 3 < len
                    && bytes[i + 1] == b'`'
                    && bytes[i + 2] == b'`'
                    && bytes[i + 3] == b'`'
                {
                    i += 4;
                    while i < len && bytes[i] != b'\n' {
                        i += 1;
                    }
                    break;
                }
                i += 1;
            }
            out.push_str(&markdown[fence_start..i]);
            continue;
        }

        // Skip inline code (` ... `)
        if bytes[i] == b'`' {
            let start = i;
            i += 1;
            while i < len && bytes[i] != b'`' {
                i += 1;
            }
            if i < len {
                i += 1;
            }
            out.push_str(&markdown[start..i]);
            continue;
        }

        // Try highlight: ==text== or =={color}text==
        if i + 1 < len && bytes[i] == b'=' && bytes[i + 1] == b'=' {
            if let Some((html, consumed)) = try_parse_highlight(&markdown[i..]) {
                out.push_str(&html);
                i += consumed;
                continue;
            }
        }

        // Try spoiler: ||text||
        if i + 1 < len && bytes[i] == b'|' && bytes[i + 1] == b'|' {
            if let Some((html, consumed)) = try_parse_spoiler(&markdown[i..]) {
                out.push_str(&html);
                i += consumed;
                continue;
            }
        }

        out.push(markdown[i..].chars().next().unwrap());
        i += markdown[i..].chars().next().unwrap().len_utf8();
    }

    out
}

/// Try to parse a highlight starting at `==`. Returns `(html, bytes_consumed)`.
fn try_parse_highlight(s: &str) -> Option<(String, usize)> {
    const VALID_COLORS: &[&str] = &[
        "red", "orange", "yellow", "green", "cyan", "blue", "violet", "pink", "brown", "grey",
    ];

    if !s.starts_with("==") {
        return None;
    }

    let after_open = &s[2..];
    if after_open.is_empty() || after_open.starts_with("==") {
        return None;
    }

    let (color, content_start) = if after_open.starts_with('{') {
        let close_brace = after_open.find('}')?;
        let color_name = &after_open[1..close_brace];
        if !VALID_COLORS.contains(&color_name) {
            return None;
        }
        (color_name, close_brace + 1)
    } else {
        ("yellow", 0)
    };

    let content_region = &after_open[content_start..];
    let close_pos = content_region.find("==")?;
    if close_pos == 0 {
        return None;
    }

    let content = &content_region[..close_pos];
    if content.contains('\n') {
        return None;
    }

    let total_consumed = 2 + content_start + close_pos + 2;
    let html = format!(
        r#"<mark data-highlight-color="{color}" class="highlight-mark highlight-{color}">{content}</mark>"#,
        color = color,
        content = html_escape(content),
    );

    Some((html, total_consumed))
}

/// Try to parse a spoiler starting at `||`. Returns `(html, bytes_consumed)`.
fn try_parse_spoiler(s: &str) -> Option<(String, usize)> {
    if !s.starts_with("||") {
        return None;
    }

    let after_open = &s[2..];
    if after_open.is_empty() || after_open.starts_with("||") {
        return None;
    }

    let close_pos = after_open.find("||")?;
    if close_pos == 0 {
        return None;
    }

    let content = &after_open[..close_pos];
    if content.contains('|') || content.contains('\n') {
        return None;
    }

    let total_consumed = 2 + close_pos + 2;
    let html = format!(
        r#"<span data-spoiler="" class="spoiler-mark spoiler-hidden">{content}</span>"#,
        content = html_escape(content),
    );

    Some((html, total_consumed))
}

// ============================================================================
// CSS
// ============================================================================

/// Get the built-in CSS stylesheet.
fn get_css() -> &'static str {
    include_str!("html_format_css.css")
}
