// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A YAML value type for frontmatter and configuration data.
 *
 * Maps to `JsonValue` in TypeScript bindings (same representation as
 * `serde_json::Value`).
 */
export type YamlValue = null | boolean | number | string | YamlValue[] | { [key: string]: YamlValue };
