#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
TARGET_DIR="${CARGO_TARGET_DIR:-$REPO_ROOT/target}"

if [ ! -d "$TARGET_DIR" ]; then
  exit 0
fi

# swift-rs writes absolute paths into Swift module cache artifacts. If the
# repository moves, stale artifacts can fail iOS builds with module cache path
# mismatch errors. Remove all swift-rs package outputs generated by Cargo build
# scripts (tauri plus tauri plugins).
#
# We must also remove the parent build-script output directories so that Cargo
# re-runs the build scripts; otherwise Cargo uses the cached output which still
# references the deleted .a files and linking fails.
for swift_dir in $(find "$TARGET_DIR" -type d -path "*/build/*/out/swift-rs" 2>/dev/null); do
  # swift_dir = .../build/<hash>/out/swift-rs
  # build_dir = .../build/<hash>
  build_dir="$(dirname "$(dirname "$swift_dir")")"
  rm -rf "$build_dir"
done
