#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
TARGET_DIR="${CARGO_TARGET_DIR:-$REPO_ROOT/target}"

if [ ! -d "$TARGET_DIR" ]; then
  exit 0
fi

# swift-rs writes absolute paths into Swift module cache artifacts. If the
# repository moves, stale artifacts can fail iOS builds with module cache path
# mismatch errors. Remove all swift-rs package outputs generated by Cargo build
# scripts (tauri plus tauri plugins).
find "$TARGET_DIR" \
  -type d \
  -path "*/build/*/out/swift-rs" \
  -prune \
  -exec rm -rf "{}" +
