name: Diaryx
options:
  bundleIdPrefix: com.diaryx
  deploymentTarget:
    macOS: "14.0"
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

targets:
  Diaryx:
    type: application
    supportedDestinations: [macOS, iOS]
    sources:
      - path: Diaryx
        type: group
    dependencies:
      - framework: diaryx_apple.xcframework
        embed: false
    postBuildScripts:
      - name: Copy Editor Bundle
        script: |
          EDITOR_DIST="${SRCROOT}/editor-bundle/dist"
          TARGET_DIR="${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/dist"
          if [ -d "${EDITOR_DIST}" ]; then
            rm -rf "${TARGET_DIR}"
            mkdir -p "${TARGET_DIR}"
            cp -R "${EDITOR_DIST}/" "${TARGET_DIR}/"
          else
            echo "warning: editor-bundle/dist not found. Run 'cd editor-bundle && bun install && bun run build' first."
          fi
        basedOnDependencyAnalysis: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.diaryx.app
        INFOPLIST_KEY_CFBundleDisplayName: Diaryx
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        PRODUCT_NAME: Diaryx
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 1
        "CODE_SIGN_ENTITLEMENTS[sdk=iphoneos*]": Diaryx/iOS.entitlements
        "CODE_SIGN_ENTITLEMENTS[sdk=iphonesimulator*]": Diaryx/iOS.entitlements
        "CODE_SIGN_ENTITLEMENTS[sdk=macosx*]": Diaryx/macOS.entitlements
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
