// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AncestorAttachmentEntry } from "./AncestorAttachmentEntry";

/**
 * Result of GetAncestorAttachments command.
 */
export type AncestorAttachmentsResult = { 
/**
 * Attachments from current entry and all ancestors.
 * Ordered from current entry first, then ancestors (closest to root).
 */
entries: Array<AncestorAttachmentEntry>, };
