// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single entry's attachments in the ancestor chain.
 */
export type AncestorAttachmentEntry = {
/**
 * Path to the entry file.
 */
entry_path: string,
/**
 * Title of the entry (from frontmatter).
 */
entry_title: string | null,
/**
 * List of attachment paths for this entry.
 */
attachments: Array<string>, };
