// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A binary file with its path and data.
 */
export type BinaryExportFile = { 
/**
 * Relative path.
 */
path: string, 
/**
 * Binary data.
 */
data: Array<number>, };
