// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Binary file path info (without data) for efficient transfer.
 * Use this when you need to list files and fetch data separately.
 */
export type BinaryFileInfo = {
/**
 * Source path (absolute, for reading).
 */
source_path: string,
/**
 * Relative path (for zip file structure).
 */
relative_path: string, };
