// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a file was excluded
 */
export type ExclusionReason = { "AudienceMismatch": {
/**
 * What audiences are intended to view the document
 */
file_audience: Array<string>,
/**
 * What audiences were requested for the export
 */
requested: string, } } | "NoAudienceDefined";
