// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedLinkResult } from "./ParsedLinkResult";

/**
 * Result of running a link parser operation.
 */
export type LinkParserResult = { "type": "parsed", "data": ParsedLinkResult } | { "type": "string", "data": string };
