// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkFormat } from "./LinkFormat";

/**
 * Link parser operation selector.
 */
export type LinkParserOperation = { "type": "parse", "params": { 
/**
 * Link string to parse.
 */
link: string, } } | { "type": "to_canonical", "params": { 
/**
 * Link string to resolve.
 */
link: string, 
/**
 * Canonical path of the file containing the link.
 */
current_file_path: string, 
/**
 * Optional hint for resolving ambiguous links.
 */
link_format_hint: LinkFormat | null, } } | { "type": "format", "params": { 
/**
 * Canonical target path.
 */
canonical_path: string, 
/**
 * Display title.
 */
title: string, 
/**
 * Output format.
 */
format: LinkFormat, 
/**
 * Canonical path of the file containing the link.
 */
from_canonical_path: string, } } | { "type": "convert", "params": { 
/**
 * Original link string.
 */
link: string, 
/**
 * Desired output format.
 */
target_format: LinkFormat, 
/**
 * Canonical path of the file containing the link.
 */
current_file_path: string, 
/**
 * Optional hint for interpreting ambiguous source links.
 */
source_format_hint: LinkFormat | null, } };
