// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Options for searching entries.
 */
export type SearchOptions = { 
/**
 * Workspace path to search in.
 */
workspace_path: string | null, 
/**
 * Whether to search frontmatter.
 */
search_frontmatter: boolean, 
/**
 * Specific property to search.
 */
property: string | null, 
/**
 * Case sensitive search.
 */
case_sensitive: boolean, };
